
export const ADD_NEWS = 'ADD_NEWS'
export const GET_NEWS = 'GET_NEWS'
export const DELETE_NEWS = 'DELETE_NEWS'

export const FETCH_NEWS_PENDING = 'FETCH_NEWS_PENDING';
export const FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS';
export const FETCH_NEWS_ERROR = 'FETCH_NEWS_ERROR';
export const UPDATE_NEWS = 'UPDATE_NEWS'